### ISSUE TITLE
Feature: datapoint with elapsing time of countdown

### ISSUE THREAD

**Issue by Scrounger** [oweitman/ioBroker.mytime#188]
Can you please provide an additional datapoint with elapsing time of countdown in ms.
Then this datapoint could be used e.g. in own widgets

**Comment by oweitman** [comment]
i think this is a bad idea, because of network traffic or message-load in vis or other vizualization.
every second (or maybe less) for each timer a new message is send to update the datapoint.
additional the time between message generation and arrival in vis is not always the same. this causes that sometimes a second is skiped.

please calculate the elapsed time from datapoints end-start.
